/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const wasm_boot: (a: number, b: number) => [number, number];
export const wasm_start: () => void;
export const main: (a: number, b: number) => number;
export const rh_rpc_enqueue: (a: number, b: number, c: number) => void;
export const rust_zstd_wasm_shim_calloc: (a: number, b: number) => number;
export const rust_zstd_wasm_shim_free: (a: number) => void;
export const rust_zstd_wasm_shim_malloc: (a: number) => number;
export const rust_zstd_wasm_shim_memcmp: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memcpy: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memmove: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_memset: (a: number, b: number, c: number) => number;
export const rust_zstd_wasm_shim_qsort: (a: number, b: number, c: number, d: number) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue__core_257c4f0f5ed5f9a0___result__Result_____wasm_bindgen_1a20cacd04d31efb___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___js_sys_48398dd4be17c34d___Function_fn_wasm_bindgen_1a20cacd04d31efb___JsValue_____wasm_bindgen_1a20cacd04d31efb___sys__Undefined___js_sys_48398dd4be17c34d___Function_fn_wasm_bindgen_1a20cacd04d31efb___JsValue_____wasm_bindgen_1a20cacd04d31efb___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__3: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__4: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__5: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__6: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__7: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__8: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__9: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__10: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke___wasm_bindgen_1a20cacd04d31efb___JsValue______true__11: (a: number, b: number, c: any) => void;
export const wasm_bindgen_1a20cacd04d31efb___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
